// +build !ignore_autogenerated

// Copyright © 2019 A Medium Corporation.
// Licensed under the Apache License, Version 2.0; see the NOTICE file.

// Code generated by defaulter. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Revision{}, func(obj interface{}) { SetObjectDefaults_Revision(obj.(*Revision)) })
	scheme.AddTypeDefaultingFunc(&RevisionList{}, func(obj interface{}) { SetObjectDefaults_RevisionList(obj.(*RevisionList)) })
	return nil
}

func SetObjectDefaults_Revision(in *Revision) {
	SetDefaults_RevisionSpec(&in.Spec)
}

func SetObjectDefaults_RevisionList(in *RevisionList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Revision(a)
	}
}
