// Copyright © 2019 A Medium Corporation.
// Licensed under the Apache License, Version 2.0; see the NOTICE file.

// Code generated by client. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.medium.engineering/picchu/pkg/apis/picchu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeReleaseManagers implements ReleaseManagerInterface
type FakeReleaseManagers struct {
	Fake *FakePicchuV1alpha1
	ns   string
}

var releasemanagersResource = schema.GroupVersionResource{Group: "picchu.medium.engineering", Version: "v1alpha1", Resource: "releasemanagers"}

var releasemanagersKind = schema.GroupVersionKind{Group: "picchu.medium.engineering", Version: "v1alpha1", Kind: "ReleaseManager"}

// Get takes name of the releaseManager, and returns the corresponding releaseManager object, and an error if there is any.
func (c *FakeReleaseManagers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ReleaseManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(releasemanagersResource, c.ns, name), &v1alpha1.ReleaseManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReleaseManager), err
}

// List takes label and field selectors, and returns the list of ReleaseManagers that match those selectors.
func (c *FakeReleaseManagers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ReleaseManagerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(releasemanagersResource, releasemanagersKind, c.ns, opts), &v1alpha1.ReleaseManagerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ReleaseManagerList{ListMeta: obj.(*v1alpha1.ReleaseManagerList).ListMeta}
	for _, item := range obj.(*v1alpha1.ReleaseManagerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested releaseManagers.
func (c *FakeReleaseManagers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(releasemanagersResource, c.ns, opts))

}

// Create takes the representation of a releaseManager and creates it.  Returns the server's representation of the releaseManager, and an error, if there is any.
func (c *FakeReleaseManagers) Create(ctx context.Context, releaseManager *v1alpha1.ReleaseManager, opts v1.CreateOptions) (result *v1alpha1.ReleaseManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(releasemanagersResource, c.ns, releaseManager), &v1alpha1.ReleaseManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReleaseManager), err
}

// Update takes the representation of a releaseManager and updates it. Returns the server's representation of the releaseManager, and an error, if there is any.
func (c *FakeReleaseManagers) Update(ctx context.Context, releaseManager *v1alpha1.ReleaseManager, opts v1.UpdateOptions) (result *v1alpha1.ReleaseManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(releasemanagersResource, c.ns, releaseManager), &v1alpha1.ReleaseManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReleaseManager), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeReleaseManagers) UpdateStatus(ctx context.Context, releaseManager *v1alpha1.ReleaseManager, opts v1.UpdateOptions) (*v1alpha1.ReleaseManager, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(releasemanagersResource, "status", c.ns, releaseManager), &v1alpha1.ReleaseManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReleaseManager), err
}

// Delete takes name of the releaseManager and deletes it. Returns an error if one occurs.
func (c *FakeReleaseManagers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(releasemanagersResource, c.ns, name, opts), &v1alpha1.ReleaseManager{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeReleaseManagers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(releasemanagersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ReleaseManagerList{})
	return err
}

// Patch applies the patch and returns the patched releaseManager.
func (c *FakeReleaseManagers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ReleaseManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(releasemanagersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ReleaseManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReleaseManager), err
}
