apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: picchu
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: picchu
  namespace: picchu
  labels:
    control-plane: picchu
spec:
  selector:
    matchLabels:
      control-plane: picchu
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: picchu
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            memory: 6Gi
          requests:
            cpu: "3"
            memory: 4Gi
      terminationGracePeriodSeconds: 10
