// Code generated by MockGen. DO NOT EDIT.
// Source: go.medium.engineering/picchu/datadog (interfaces: DatadogMonitorAPI)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=prometheus/mocks/mock_datadogmonitorapi.go -package=mocks go.medium.engineering/picchu/datadog DatadogMonitorAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	datadogV1 "github.com/DataDog/datadog-api-client-go/v2/api/datadogV1"
	gomock "go.uber.org/mock/gomock"
)

// MockDatadogMonitorAPI is a mock of DatadogMonitorAPI interface.
type MockDatadogMonitorAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDatadogMonitorAPIMockRecorder
}

// MockDatadogMonitorAPIMockRecorder is the mock recorder for MockDatadogMonitorAPI.
type MockDatadogMonitorAPIMockRecorder struct {
	mock *MockDatadogMonitorAPI
}

// NewMockDatadogMonitorAPI creates a new mock instance.
func NewMockDatadogMonitorAPI(ctrl *gomock.Controller) *MockDatadogMonitorAPI {
	mock := &MockDatadogMonitorAPI{ctrl: ctrl}
	mock.recorder = &MockDatadogMonitorAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatadogMonitorAPI) EXPECT() *MockDatadogMonitorAPIMockRecorder {
	return m.recorder
}

// ListMonitors mocks base method.
func (m *MockDatadogMonitorAPI) ListMonitors(arg0 context.Context, arg1 ...datadogV1.ListMonitorsOptionalParameters) ([]datadogV1.Monitor, *http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMonitors", varargs...)
	ret0, _ := ret[0].([]datadogV1.Monitor)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMonitors indicates an expected call of ListMonitors.
func (mr *MockDatadogMonitorAPIMockRecorder) ListMonitors(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMonitors", reflect.TypeOf((*MockDatadogMonitorAPI)(nil).ListMonitors), varargs...)
}

// SearchMonitorGroups mocks base method.
func (m *MockDatadogMonitorAPI) SearchMonitorGroups(arg0 context.Context, arg1 ...datadogV1.SearchMonitorGroupsOptionalParameters) (datadogV1.MonitorGroupSearchResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchMonitorGroups", varargs...)
	ret0, _ := ret[0].(datadogV1.MonitorGroupSearchResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchMonitorGroups indicates an expected call of SearchMonitorGroups.
func (mr *MockDatadogMonitorAPIMockRecorder) SearchMonitorGroups(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMonitorGroups", reflect.TypeOf((*MockDatadogMonitorAPI)(nil).SearchMonitorGroups), varargs...)
}

// SearchMonitors mocks base method.
func (m *MockDatadogMonitorAPI) SearchMonitors(arg0 context.Context, arg1 ...datadogV1.SearchMonitorsOptionalParameters) (datadogV1.MonitorSearchResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchMonitors", varargs...)
	ret0, _ := ret[0].(datadogV1.MonitorSearchResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchMonitors indicates an expected call of SearchMonitors.
func (mr *MockDatadogMonitorAPIMockRecorder) SearchMonitors(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMonitors", reflect.TypeOf((*MockDatadogMonitorAPI)(nil).SearchMonitors), varargs...)
}
