// Copyright © 2019 A Medium Corporation.
// Licensed under the Apache License, Version 2.0; see the LICENSE file.

// Code generated by client. DO NOT EDIT.

package v1alpha1

type ClusterExpansion interface{}

type IncarnationExpansion interface{}

type RevisionExpansion interface{}
