// Copyright © 2019 A Medium Corporation.
// Licensed under the Apache License, Version 2.0; see the NOTICE file.

// Code generated by client. DO NOT EDIT.

package v1alpha1

type ClusterExpansion interface{}

type ReleaseManagerExpansion interface{}

type RevisionExpansion interface{}
