// Copyright © 2019 A Medium Corporation.
// Licensed under the Apache License, Version 2.0; see the NOTICE file.

// Code generated by client. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "go.medium.engineering/picchu/pkg/apis/picchu/v1alpha1"
	scheme "go.medium.engineering/picchu/pkg/client/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IncarnationsGetter has a method to return a IncarnationInterface.
// A group's client should implement this interface.
type IncarnationsGetter interface {
	Incarnations(namespace string) IncarnationInterface
}

// IncarnationInterface has methods to work with Incarnation resources.
type IncarnationInterface interface {
	Create(*v1alpha1.Incarnation) (*v1alpha1.Incarnation, error)
	Update(*v1alpha1.Incarnation) (*v1alpha1.Incarnation, error)
	UpdateStatus(*v1alpha1.Incarnation) (*v1alpha1.Incarnation, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Incarnation, error)
	List(opts v1.ListOptions) (*v1alpha1.IncarnationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Incarnation, err error)
	IncarnationExpansion
}

// incarnations implements IncarnationInterface
type incarnations struct {
	client rest.Interface
	ns     string
}

// newIncarnations returns a Incarnations
func newIncarnations(c *PicchuV1alpha1Client, namespace string) *incarnations {
	return &incarnations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the incarnation, and returns the corresponding incarnation object, and an error if there is any.
func (c *incarnations) Get(name string, options v1.GetOptions) (result *v1alpha1.Incarnation, err error) {
	result = &v1alpha1.Incarnation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("incarnations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Incarnations that match those selectors.
func (c *incarnations) List(opts v1.ListOptions) (result *v1alpha1.IncarnationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IncarnationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("incarnations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested incarnations.
func (c *incarnations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("incarnations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a incarnation and creates it.  Returns the server's representation of the incarnation, and an error, if there is any.
func (c *incarnations) Create(incarnation *v1alpha1.Incarnation) (result *v1alpha1.Incarnation, err error) {
	result = &v1alpha1.Incarnation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("incarnations").
		Body(incarnation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a incarnation and updates it. Returns the server's representation of the incarnation, and an error, if there is any.
func (c *incarnations) Update(incarnation *v1alpha1.Incarnation) (result *v1alpha1.Incarnation, err error) {
	result = &v1alpha1.Incarnation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("incarnations").
		Name(incarnation.Name).
		Body(incarnation).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *incarnations) UpdateStatus(incarnation *v1alpha1.Incarnation) (result *v1alpha1.Incarnation, err error) {
	result = &v1alpha1.Incarnation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("incarnations").
		Name(incarnation.Name).
		SubResource("status").
		Body(incarnation).
		Do().
		Into(result)
	return
}

// Delete takes name of the incarnation and deletes it. Returns an error if one occurs.
func (c *incarnations) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("incarnations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *incarnations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("incarnations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched incarnation.
func (c *incarnations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Incarnation, err error) {
	result = &v1alpha1.Incarnation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("incarnations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
