// Copyright © 2019 A Medium Corporation.
// Licensed under the Apache License, Version 2.0; see the NOTICE file.

// Code generated by client. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "go.medium.engineering/picchu/pkg/apis/picchu/v1alpha1"
	scheme "go.medium.engineering/picchu/pkg/client/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ReleaseManagersGetter has a method to return a ReleaseManagerInterface.
// A group's client should implement this interface.
type ReleaseManagersGetter interface {
	ReleaseManagers(namespace string) ReleaseManagerInterface
}

// ReleaseManagerInterface has methods to work with ReleaseManager resources.
type ReleaseManagerInterface interface {
	Create(*v1alpha1.ReleaseManager) (*v1alpha1.ReleaseManager, error)
	Update(*v1alpha1.ReleaseManager) (*v1alpha1.ReleaseManager, error)
	UpdateStatus(*v1alpha1.ReleaseManager) (*v1alpha1.ReleaseManager, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ReleaseManager, error)
	List(opts v1.ListOptions) (*v1alpha1.ReleaseManagerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ReleaseManager, err error)
	ReleaseManagerExpansion
}

// releaseManagers implements ReleaseManagerInterface
type releaseManagers struct {
	client rest.Interface
	ns     string
}

// newReleaseManagers returns a ReleaseManagers
func newReleaseManagers(c *PicchuV1alpha1Client, namespace string) *releaseManagers {
	return &releaseManagers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the releaseManager, and returns the corresponding releaseManager object, and an error if there is any.
func (c *releaseManagers) Get(name string, options v1.GetOptions) (result *v1alpha1.ReleaseManager, err error) {
	result = &v1alpha1.ReleaseManager{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("releasemanagers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ReleaseManagers that match those selectors.
func (c *releaseManagers) List(opts v1.ListOptions) (result *v1alpha1.ReleaseManagerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ReleaseManagerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("releasemanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested releaseManagers.
func (c *releaseManagers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("releasemanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a releaseManager and creates it.  Returns the server's representation of the releaseManager, and an error, if there is any.
func (c *releaseManagers) Create(releaseManager *v1alpha1.ReleaseManager) (result *v1alpha1.ReleaseManager, err error) {
	result = &v1alpha1.ReleaseManager{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("releasemanagers").
		Body(releaseManager).
		Do().
		Into(result)
	return
}

// Update takes the representation of a releaseManager and updates it. Returns the server's representation of the releaseManager, and an error, if there is any.
func (c *releaseManagers) Update(releaseManager *v1alpha1.ReleaseManager) (result *v1alpha1.ReleaseManager, err error) {
	result = &v1alpha1.ReleaseManager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("releasemanagers").
		Name(releaseManager.Name).
		Body(releaseManager).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *releaseManagers) UpdateStatus(releaseManager *v1alpha1.ReleaseManager) (result *v1alpha1.ReleaseManager, err error) {
	result = &v1alpha1.ReleaseManager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("releasemanagers").
		Name(releaseManager.Name).
		SubResource("status").
		Body(releaseManager).
		Do().
		Into(result)
	return
}

// Delete takes name of the releaseManager and deletes it. Returns an error if one occurs.
func (c *releaseManagers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("releasemanagers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *releaseManagers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("releasemanagers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched releaseManager.
func (c *releaseManagers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ReleaseManager, err error) {
	result = &v1alpha1.ReleaseManager{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("releasemanagers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
