
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-picchu-medium-engineering-v1alpha1-revision
  failurePolicy: Fail
  name: mrevision.kb.io
  rules:
  - apiGroups:
    - picchu.medium.engineering
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - revisions
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-picchu-medium-engineering-v1alpha1-revision
  failurePolicy: Fail
  name: vrevision.kb.io
  rules:
  - apiGroups:
    - picchu.medium.engineering
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - revisions
  sideEffects: None
