apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: picchu
  name: picchu-metrics-service
  namespace: picchu
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: picchu
