# permissions for end users to edit clustersecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustersecrets-editor-role
rules:
- apiGroups:
  - picchu.medium.engineering
  resources:
  - clustersecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - picchu.medium.engineering
  resources:
  - clustersecrets/status
  verbs:
  - get
