# permissions for end users to view faultinjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: faultinjector-viewer-role
rules:
- apiGroups:
  - picchu.medium.engineering
  resources:
  - faultinjectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - picchu.medium.engineering
  resources:
  - faultinjectors/status
  verbs:
  - get
