# permissions for end users to edit faultinjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: faultinjector-editor-role
rules:
- apiGroups:
  - picchu.medium.engineering
  resources:
  - faultinjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - picchu.medium.engineering
  resources:
  - faultinjectors/status
  verbs:
  - get
