apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: picchu-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: picchu-leader-election-role
subjects:
- kind: ServiceAccount
  name: picchu
  namespace: picchu
