
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role-extra
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - picchu.medium.engineering
  resources:
  - mirrors
  - faultinjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
