---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: picchu-manager-role
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - external-secrets.io
  resources:
  - clustersecretstores
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets/finalizers
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets/status
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - picchu.medium.engineering
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - picchu.medium.engineering
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - picchu.medium.engineering
  resources:
  - clustersecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - picchu.medium.engineering
  resources:
  - clustersecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - picchu.medium.engineering
  resources:
  - releasemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - picchu.medium.engineering
  resources:
  - releasemanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - picchu.medium.engineering
  resources:
  - revisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - picchu.medium.engineering
  resources:
  - revisions/status
  verbs:
  - get
  - patch
  - update
