apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    categories:
    - all
    - picchu
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Cluster is the Schema for the clusters API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterSpec defines the desired state of Cluster
            properties:
              config:
                properties:
                  certificate-authority-data:
                    format: byte
                    type: string
                  server:
                    type: string
                required:
                - certificate-authority-data
                - server
                type: object
              devRouteTagTemplate:
                type: string
              enableDevRoutes:
                type: boolean
              enabled:
                type: boolean
              hotStandby:
                type: boolean
              ingresses:
                description: ScalingFactor       *resource.Quantity `json:"scalingFactor,omitempty"`
                properties:
                  private:
                    properties:
                      defaultDomains:
                        items:
                          type: string
                        type: array
                      dnsName:
                        type: string
                      gateway:
                        type: string
                    required:
                    - defaultDomains
                    - dnsName
                    type: object
                  public:
                    properties:
                      defaultDomains:
                        items:
                          type: string
                        type: array
                      dnsName:
                        type: string
                      gateway:
                        type: string
                    required:
                    - defaultDomains
                    - dnsName
                    type: object
                required:
                - private
                - public
                type: object
              scalingFactorString:
                description: Replace with resource.Quantity when upgrading to client-go
                  1.20.x
                type: string
            required:
            - enabled
            - ingresses
            type: object
          status:
            description: ClusterStatus defines the observed state of Cluster
            properties:
              kubernetes:
                properties:
                  ready:
                    type: boolean
                  version:
                    type: string
                required:
                - ready
                - version
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
