apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: incarnations.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: Incarnation
    listKind: IncarnationList
    plural: incarnations
    singular: incarnation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            app:
              properties:
                name:
                  type: string
                tag:
                  type: string
              required:
              - name
              - tag
              type: object
            assignment:
              properties:
                name:
                  type: string
              required:
              - name
              type: object
            release:
              properties:
                max:
                  format: int64
                  type: integer
                rate:
                  type: string
                schedule:
                  type: string
              required:
              - max
              - rate
              - schedule
              type: object
            scale:
              properties:
                max:
                  format: int64
                  type: integer
                min:
                  format: int64
                  type: integer
                resources:
                  items:
                    properties:
                      cpu:
                        type: string
                    required:
                    - cpu
                    type: object
                  type: array
              required:
              - min
              - max
              - resources
              type: object
          required:
          - app
          - assignment
          - scale
          - release
          type: object
        status:
          properties:
            health:
              properties:
                healthy:
                  type: boolean
                metrics:
                  items:
                    properties:
                      actual:
                        format: double
                        type: number
                      name:
                        type: string
                      objective:
                        format: double
                        type: number
                    required:
                    - name
                    - objective
                    - actual
                    type: object
                  type: array
              required:
              - healthy
              - metrics
              type: object
            release:
              properties:
                currentPercent:
                  format: int64
                  type: integer
                peakPercent:
                  format: int64
                  type: integer
              required:
              - peakPercent
              - currentPercent
              type: object
            resources:
              items:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  metadata:
                    type: object
                  status:
                    type: string
                required:
                - apiVersion
                - kind
                - metadata
                - status
                type: object
              type: array
            scale:
              properties:
                current:
                  format: int64
                  type: integer
                desired:
                  format: int64
                  type: integer
              required:
              - current
              - desired
              type: object
          required:
          - health
          - release
          - scale
          - resources
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
