apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: revisions.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: Revision
    listKind: RevisionList
    plural: revisions
    singular: revision
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            app:
              properties:
                image:
                  type: string
                name:
                  type: string
                ref:
                  type: string
                tag:
                  type: string
              required:
              - name
              - ref
              - tag
              - image
              type: object
            ports:
              items:
                properties:
                  containerPort:
                    format: int32
                    type: integer
                  hosts:
                    items:
                      type: string
                    type: array
                  mode:
                    type: string
                  name:
                    type: string
                  port:
                    format: int32
                    type: integer
                  protocol:
                    type: string
                required:
                - mode
                type: object
              type: array
            release:
              properties:
                eligible:
                  type: boolean
              required:
              - eligible
              type: object
            targets:
              items:
                properties:
                  fleet:
                    type: string
                  metrics:
                    items:
                      properties:
                        name:
                          type: string
                        objective:
                          format: double
                          type: number
                        queries:
                          properties:
                            acceptable:
                              type: string
                            total:
                              type: string
                          required:
                          - acceptable
                          - total
                          type: object
                      required:
                      - name
                      - queries
                      - objective
                      type: object
                    type: array
                  name:
                    type: string
                  release:
                    properties:
                      eligible:
                        type: boolean
                      max:
                        format: int32
                        type: integer
                      rate:
                        properties:
                          delaySeconds:
                            format: int32
                            type: integer
                          increment:
                            format: int32
                            type: integer
                        type: object
                      schedule:
                        type: string
                    type: object
                  scale:
                    properties:
                      default:
                        format: int32
                        type: integer
                      max:
                        format: int32
                        type: integer
                      min:
                        format: int32
                        type: integer
                      resources:
                        properties:
                          cpu:
                            type: string
                        type: object
                    type: object
                required:
                - name
                - fleet
                - scale
                type: object
              type: array
          required:
          - app
          - release
          - ports
          - targets
          type: object
        status:
          properties:
            targets:
              items:
                properties:
                  incarnations:
                    items:
                      properties:
                        cluster:
                          type: string
                        name:
                          type: string
                        status:
                          type: string
                      required:
                      - name
                      - cluster
                      - status
                      type: object
                    type: array
                  name:
                    type: string
                required:
                - name
                - incarnations
                type: object
              type: array
          required:
          - targets
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
