apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusters.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    categories:
    - all
    - picchu
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Cluster is the Schema for the clusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClusterSpec defines the desired state of Cluster
          properties:
            aws:
              properties:
                accountId:
                  type: string
                az:
                  type: string
                region:
                  type: string
              required:
              - accountId
              - region
              type: object
            config:
              properties:
                certificate-authority-data:
                  format: byte
                  type: string
                server:
                  type: string
              required:
              - certificate-authority-data
              - server
              type: object
            defaultDomain:
              type: string
            defaultDomains:
              items:
                type: string
              type: array
            dns:
              items:
                properties:
                  hosts:
                    items:
                      type: string
                    type: array
                  ingress:
                    type: string
                  provider:
                    type: string
                type: object
              type: array
            enabled:
              type: boolean
            hotStandby:
              type: boolean
            ingresses:
              properties:
                private:
                  properties:
                    dnsName:
                      type: string
                    gateway:
                      type: string
                    hostedZoneId:
                      type: string
                  required:
                  - dnsName
                  - hostedZoneId
                  type: object
                public:
                  properties:
                    dnsName:
                      type: string
                    gateway:
                      type: string
                    hostedZoneId:
                      type: string
                  required:
                  - dnsName
                  - hostedZoneId
                  type: object
              required:
              - private
              - public
              type: object
            scalingFactor: {}
            useNewTagStyle:
              type: boolean
            weight: {}
          required:
          - enabled
          - ingresses
          - weight
          type: object
        status:
          description: ClusterStatus defines the observed state of Cluster
          properties:
            aws:
              properties:
                accountId:
                  type: string
                az:
                  type: string
                region:
                  type: string
              required:
              - accountId
              - region
              type: object
            conditions:
              items:
                properties:
                  name:
                    type: string
                  status:
                    type: string
                required:
                - name
                - status
                type: object
              type: array
            kubernetes:
              properties:
                version:
                  type: string
              required:
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
