apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: revisions.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: Revision
    plural: revisions
    categories:
    - all
    - picchu
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            failed:
              type: boolean
            ignoreSLOs:
              type: boolean
            app:
              properties:
                image:
                  type: string
                name:
                  type: string
                ref:
                  type: string
                tag:
                  type: string
              required:
              - name
              - ref
              - tag
              - image
              type: object
            alertRules:
              items:
                description: Rule describes an alerting or recording rule.
                properties:
                  alert:
                    type: string
                  annotations:
                    type: object
                  expr:
                    anyOf:
                    - type: string
                    - type: integer
                  for:
                    type: string
                  labels:
                    type: object
                  record:
                    type: string
                required:
                - expr
              type: array
            ports:
              items:
                properties:
                  containerPort:
                    format: int32
                    type: integer
                  hosts:
                    items:
                      type: string
                    type: array
                  ingressPort:
                    format: int32
                    type: integer
                  mode:
                    type: string
                  name:
                    type: string
                  port:
                    format: int32
                    type: integer
                  protocol:
                    type: string
                required:
                - name
                - mode
                type: object
              type: array
            targets:
              items:
                properties:
                  aws:
                    properties:
                      iam:
                        properties:
                          role_arn:
                            type: string
                        type: object
                    type: object
                  configSelector:
                    type: object
                  fleet:
                    type: string
                  metrics:
                    items:
                      properties:
                        name:
                          type: string
                        objective:
                          format: double
                          type: number
                        queries:
                          properties:
                            acceptable:
                              type: string
                            total:
                              type: string
                          required:
                          - acceptable
                          - total
                          type: object
                      required:
                      - name
                      - queries
                      - objective
                      type: object
                    type: array
                  name:
                    type: string
                  release:
                    properties:
                      eligible:
                        type: boolean
                      max:
                        format: int32
                        type: integer
                      rate:
                        properties:
                          delay:
                            format: int64
                            type: integer
                          increment:
                            format: int32
                            type: integer
                        type: object
                      schedule:
                        type: string
                      ttl:
                        format: int64
                        type: integer
                    type: object
                  resources:
                    properties:
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                  scale:
                    properties:
                      default:
                        format: int32
                        type: integer
                      max:
                        format: int32
                        type: integer
                      min:
                        format: int32
                        type: integer
                      resources:
                        description: Deprecated. Use TargetCPUUtilizationPercentage.
                        properties:
                          cpu:
                            type: string
                        type: object
                      targetCPUUtilizationPercentage:
                        format: int32
                        type: integer
                    type: object
                required:
                - name
                - fleet
                - scale
                type: object
              type: array
          required:
          - app
          - ports
          - targets
          type: object
        status:
          type: object
          properties:
            targets:
              type: array
              items:
                clusters:
                  type: object
                  properties:
                    count:
                      format: int32
                      type: integer
                    minPercent:
                      format: int32
                      type: integer
                    maxPercent:
                      format: int32
                      type: integer
                    names:
                      items:
                        type: string
                      type: array
                    releaseCount:
                      format: int32
                      type: integer
                release:
                  type: object
                  properties:
                    currentPercent:
                      format: int32
                      type: integer
                    peakPercent:
                      format: int32
                      type: integer
                scale:
                  type: object
                  properties:
                    current:
                      format: int32
                      type: integer
                    desired:
                      format: int32
                      type: integer
                    peak:
                      format: int32
                      type: integer
                externalTest:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    started:
                      type: boolean
                    completed:
                      type: boolean
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
