apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: faultinjectors.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: FaultInjector
    listKind: FaultInjectorList
    plural: faultinjectors
    singular: faultinjector
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FaultInjector is the Schema for the faultinjectors API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FaultInjectorSpec defines the desired state of FaultInjector
            properties:
              httpPortFaults:
                items:
                  description: HTTPPortFault allows injecting faults into apps by
                    port number
                  properties:
                    fault:
                      properties:
                        abort:
                          properties:
                            error_type:
                              properties:
                                grpc_status:
                                  type: string
                                http_status:
                                  format: int32
                                  type: integer
                                http2_error:
                                  type: string
                              type: object
                            percentage:
                              properties:
                                value:
                                  anyOf:
                                  - type: integer
                                  - type: string
                                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                  x-kubernetes-int-or-string: true
                              type: object
                          type: object
                        delay:
                          properties:
                            http_delay_type:
                              properties:
                                exponential_delay:
                                  $ref: '#/definitions/github.com~1gogo~1protobuf~1types~0Duration'
                                fixed_delay:
                                  $ref: '#/definitions/github.com~1gogo~1protobuf~1types~0Duration'
                              type: object
                            percent:
                              format: int32
                              type: integer
                            percentage:
                              properties:
                                value:
                                  anyOf:
                                  - type: integer
                                  - type: string
                                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                  x-kubernetes-int-or-string: true
                              type: object
                          type: object
                      type: object
                    portSelector:
                      properties:
                        number:
                          format: int32
                          type: integer
                      type: object
                  type: object
                type: array
            required:
            - httpPortFaults
            type: object
          status:
            description: FaultInjectorStatus defines the observed state of FaultInjector
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
