apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: releasemanagers.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: ReleaseManager
    plural: releasemanagers
    categories:
    - all
    - picchu
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            app:
              type: string
            fleet:
              type: string
            target:
              type: string
          required:
          - fleet
          - app
          - target
          type: object
        status:
          properties:
            revisions:
              items:
                properties:
                  ttl:
                    format: int64
                    type: integer
                  metrics:
                    properties:
                      gitReleaseSeconds:
                        format: double
                        type: number
                      gitDeploySeconds:
                        format: double
                        type: number
                      revisionDeploySeconds:
                        format: double
                        type: number
                    type: object
                  currentPercent:
                    format: int32
                    type: integer
                  lastUpdated:
                    format: date-time
                    type: string
                  peakPercent:
                    format: int32
                    type: integer
                  tag:
                    type: string
                  releasEligible:
                    type: boolean
                  deployed:
                    type: boolean
                  revisionTimestamp:
                    type: string
                  canaryStartTimestamp:
                    type: string
                  gitTimestamp:
                    type: string
                  state:
                    type: object
                    properties:
                      current:
                        type: string
                      target:
                        type: string
                  scale:
                    properties:
                      current:
                        format: int32
                        type: integer
                      desired:
                        format: int32
                        type: integer
                      peak:
                        format: int32
                        type: integer
                    type: object
                  resources:
                    items:
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        metadata:
                          type: object
                      type: object
                    type: array
                required:
                - tag
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
