apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustersecrets.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: ClusterSecrets
    listKind: ClusterSecretsList
    plural: clustersecrets
    singular: clustersecret
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
