apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: revisions.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: Revision
    plural: revisions
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            app:
              properties:
                image:
                  type: string
                name:
                  type: string
                ref:
                  type: string
                tag:
                  type: string
              required:
              - name
              - ref
              - tag
              - image
              type: object
            ports:
              items:
                properties:
                  containerPort:
                    format: int32
                    type: integer
                  hosts:
                    items:
                      type: string
                    type: array
                  ingressPort:
                    format: int32
                    type: integer
                  mode:
                    type: string
                  name:
                    type: string
                  port:
                    format: int32
                    type: integer
                  protocol:
                    type: string
                required:
                - name
                - mode
                type: object
              type: array
            release:
              properties:
                eligible:
                  type: boolean
              required:
              - eligible
              type: object
            targets:
              items:
                properties:
                  configSelector:
                    type: object
                  fleet:
                    type: string
                  metrics:
                    items:
                      properties:
                        name:
                          type: string
                        objective:
                          format: double
                          type: number
                        queries:
                          properties:
                            acceptable:
                              type: string
                            total:
                              type: string
                          required:
                          - acceptable
                          - total
                          type: object
                      required:
                      - name
                      - queries
                      - objective
                      type: object
                    type: array
                  name:
                    type: string
                  release:
                    properties:
                      eligible:
                        type: boolean
                      max:
                        format: int32
                        type: integer
                      rate:
                        properties:
                          delay:
                            format: int64
                            type: integer
                          increment:
                            format: int32
                            type: integer
                        type: object
                      schedule:
                        type: string
                    type: object
                  scale:
                    properties:
                      default:
                        format: int32
                        type: integer
                      max:
                        format: int32
                        type: integer
                      min:
                        format: int32
                        type: integer
                      resources:
                        properties:
                          cpu:
                            type: string
                        type: object
                      targetCPUUtilizationPercentage:
                        format: int32
                        type: integer
                    type: object
                required:
                - name
                - fleet
                - scale
                type: object
              type: array
          required:
          - app
          - release
          - ports
          - targets
          type: object
        status:
          properties:
            incarnations:
              items:
                properties:
                  cluster:
                    type: string
                  name:
                    type: string
                  status:
                    type: string
                  target:
                    type: string
                required:
                - name
                - cluster
                - status
                - target
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
