apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: clusters.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            aws:
              properties:
                accountId:
                  type: string
                az:
                  type: string
                region:
                  type: string
              required:
              - accountId
              - region
              type: object
            config:
              properties:
                server:
                  type: string
              required:
              - server
              type: object
            dns:
              items:
                properties:
                  hosts:
                    items:
                      type: string
                    type: array
                  ingress:
                    type: string
                  provider:
                    type: string
                type: object
              type: array
            enabled:
              type: boolean
            ingresses:
              properties:
                private:
                  type: object
                public:
                  type: object
              required:
              - public
              - private
              type: object
            weight:
              format: double
              type: number
          required:
          - enabled
          - weight
          - ingresses
          type: object
        status:
          properties:
            aws:
              properties:
                accountId:
                  type: string
                az:
                  type: string
                region:
                  type: string
              required:
              - accountId
              - region
              type: object
            conditions:
              items:
                properties:
                  name:
                    type: string
                  status:
                    type: string
                required:
                - name
                - status
                type: object
              type: array
            kubernetes:
              properties:
                version:
                  type: string
              required:
              - version
              type: object
          required:
          - kubernetes
          - conditions
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
