apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusters.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: Cluster
    plural: clusters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            aws:
              properties:
                accountId:
                  type: string
                az:
                  type: string
                region:
                  type: string
              required:
              - accountId
              - region
              type: object
            config:
              properties:
                server:
                  type: string
              required:
              - server
              type: object
            defaultDomain:
              type: string
            dns:
              items:
                properties:
                  hosts:
                    items:
                      type: string
                    type: array
                  ingress:
                    type: string
                  provider:
                    type: string
                type: object
              type: array
            enabled:
              type: boolean
            ingresses:
              properties:
                private:
                  properties:
                    dnsName:
                      type: string
                    gateway:
                      type: string
                    hostedZoneId:
                      type: string
                  required:
                  - hostedZoneId
                  - dnsName
                  type: object
                public:
                  properties:
                    dnsName:
                      type: string
                    gateway:
                      type: string
                    hostedZoneId:
                      type: string
                  required:
                  - hostedZoneId
                  - dnsName
                  type: object
              required:
              - public
              - private
              type: object
            weight:
              format: double
              type: number
          required:
          - enabled
          - weight
          - ingresses
          - defaultDomain
          type: object
        status:
          properties:
            aws:
              properties:
                accountId:
                  type: string
                az:
                  type: string
                region:
                  type: string
              required:
              - accountId
              - region
              type: object
            conditions:
              items:
                properties:
                  name:
                    type: string
                  status:
                    type: string
                required:
                - name
                - status
                type: object
              type: array
            kubernetes:
              properties:
                version:
                  type: string
              required:
              - version
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
