apiVersion: picchu.medium.engineering/v1alpha1
kind: Revision
metadata:
  name: 'lite-master-20190301-130000-24e07cb7399' # could also use generateName:
  labels:
    medium.build/app: 'lite'
    medium.build/tag: 'master-20190301-130000-24e07cb7399' # Docker image tag
    medium.build/commit: '24e07cb7399e1e76de6103a0548a0ef2e471e43f'
    app.kubernetes.io/managed-by: 'kbfd' # recommended Kubernetes label
spec:
  app:
    name: 'lite'
    ref: 'master' # non-master branches can get their own DNS names for testing
    tag: 'master-20190301-130000-24e07cb7399'
  releaseEligible:
    eligible: true
    # set eligible to true to make the Revision eligible for automatic release
    # set eligible to false to rollback a Revision already getting traffic
  ports:
  - name: http
    containerPort: 5000
  targets:
  - name: hatch
    fleet: hatch
    scale:
      min: 2
      max: 4
      resources: {cpu: 500m}
  - name: production
    fleet: legacy
    release:
      max: 100
      # set to 0 to disable automatic release, set to less than 100 to cap the
      # release at that percentage
      rate: TK # rollout rate
      schedule: humane # limit to working hours; set to always to release whenever
    metrics:
      # inspired by https://github.com/spotahome/service-level-operator
      - name: availability
        queries:
          acceptable: '...'
          total: '...'
        objective: 0.99 # acceptable รท total
      - name: latency
        # ...
    scale:
      min: 24
      max: 72
      # in a pinch, we'll be able to scale an app by editing the Revision
      # (should the pod numbers be per-cluster, or total?)
      resources: {cpu: 500m}
