apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: incarnations.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: Incarnation
    listKind: IncarnationList
    plural: incarnations
    singular: incarnation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            app:
              properties:
                image:
                  type: string
                name:
                  type: string
                ref:
                  type: string
                tag:
                  type: string
              required:
              - name
              - tag
              - ref
              - image
              type: object
            assignment:
              properties:
                name:
                  type: string
                target:
                  type: string
              required:
              - name
              - target
              type: object
            ports:
              items:
                properties:
                  containerPort:
                    format: int32
                    type: integer
                  hosts:
                    items:
                      type: string
                    type: array
                  mode:
                    type: string
                  name:
                    type: string
                  port:
                    format: int32
                    type: integer
                  protocol:
                    type: string
                required:
                - mode
                type: object
              type: array
            release:
              properties:
                eligible:
                  type: boolean
                max:
                  format: int32
                  type: integer
                rate:
                  properties:
                    delaySeconds:
                      format: int32
                      type: integer
                    increment:
                      format: int32
                      type: integer
                  type: object
                schedule:
                  type: string
              type: object
            scale:
              properties:
                default:
                  format: int32
                  type: integer
                max:
                  format: int32
                  type: integer
                min:
                  format: int32
                  type: integer
                resources:
                  properties:
                    cpu:
                      type: string
                  type: object
              type: object
          required:
          - app
          - assignment
          - scale
          type: object
        status:
          properties:
            health:
              properties:
                healthy:
                  type: boolean
                metrics:
                  items:
                    properties:
                      actual:
                        format: double
                        type: number
                      name:
                        type: string
                      objective:
                        format: double
                        type: number
                    type: object
                  type: array
              type: object
            release:
              properties:
                currentPercent:
                  format: int32
                  type: integer
                lastUpdate:
                  type: string
                peakPercent:
                  format: int32
                  type: integer
              type: object
            resources:
              items:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  metadata:
                    type: object
                  status:
                    type: string
                required:
                - apiVersion
                - kind
                - status
                type: object
              type: array
            scale:
              properties:
                current:
                  format: int32
                  type: integer
                desired:
                  format: int32
                  type: integer
              required:
              - current
              - desired
              type: object
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
