apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustersecrets.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: ClusterSecrets
    listKind: ClusterSecretsList
    plural: clustersecrets
    singular: clustersecrets
  scope: ""
  validation:
    openAPIV3Schema:
      description: ClusterSecrets is the Schema for the clustersecrets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClusterSecretsSpec defines the desired state of ClusterSecrets
          properties:
            source:
              properties:
                fieldSelector:
                  type: string
                labelSelector:
                  type: string
                namespace:
                  type: string
              required:
              - namespace
              type: object
            target:
              properties:
                annotations:
                  additionalProperties:
                    type: string
                  description: Annotations to add to the copied secrets
                  type: object
                fieldSelector:
                  description: FieldSelector of clusters to copy secrets to
                  type: string
                labelSelector:
                  description: LabelSelector of clusters to copy secrets to
                  type: string
                labels:
                  additionalProperties:
                    type: string
                  description: Labels to add to the copied secrets
                  type: object
                namespace:
                  description: Namespace to copy secrets to
                  type: string
              required:
              - namespace
              type: object
          required:
          - source
          - target
          type: object
        status:
          description: ClusterSecretsStatus defines the observed state of ClusterSecrets
          properties:
            secrets:
              description: Names of secrets copied to targets
              items:
                type: string
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
