apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mirrors.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: Mirror
    listKind: MirrorList
    plural: mirrors
    singular: mirror
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            clusterName:
              type: string
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
