apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: releasemanagers.picchu.medium.engineering
spec:
  group: picchu.medium.engineering
  names:
    kind: ReleaseManager
    plural: releasemanagers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            app:
              type: string
            cluster:
              type: string
            target:
              type: string
          required:
          - cluster
          - app
          - target
          type: object
        status:
          properties:
            releases:
              items:
                properties:
                  currentPercent:
                    format: int32
                    type: integer
                  lastUpdated:
                    format: date-time
                    type: string
                  peakPercent:
                    format: int32
                    type: integer
                  tag:
                    type: string
                  released:
                    type: boolean
                required:
                - tag
                - lastUpdated
                - currentPercent
                - peakPercent
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
