---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: picchu/serving-cert
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: picchu
      path: /mutate-picchu-medium-engineering-v1alpha1-revision
  failurePolicy: Fail
  name: mrevision.kb.io
  rules:
  - apiGroups:
    - picchu.medium.engineering
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - revisions
  sideEffects: None
