apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: picchu
  name: picchu
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: picchu
  name: picchu
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: picchu
  name: picchu
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: picchu
  name: picchu
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: picchu
  name: picchu
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: picchu
  name: picchu
