apiVersion: apps/v1
kind: Deployment
metadata:
  name: picchu
  namespace: picchu
spec:
  replicas: 1
  selector:
    matchLabels:
      name: picchu
  template:
    metadata:
      labels:
        name: picchu
    spec:
      serviceAccountName: picchu
      containers:
        - name: picchu
          # Replace this with the built image name
          image: docker.medium.build/picchu
          command:
          - picchu
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "picchu"
