kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: picchu
  namespace: picchu
subjects:
- kind: ServiceAccount
  name: picchu
roleRef:
  kind: Role
  name: picchu
  apiGroup: rbac.authorization.k8s.io
