kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: picchu
subjects:
- kind: ServiceAccount
  name: picchu
  namespace: picchu
roleRef:
  kind: ClusterRole
  name: picchu
  apiGroup: rbac.authorization.k8s.io
