---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: picchu
  namespace: picchu
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: picchu
  namespace: picchu
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: picchu
  namespace: picchu
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: picchu
  namespace: picchu
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: picchu
  namespace: picchu
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: picchu
  namespace: picchu
