- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/targets/items/properties/sidecars/items/properties/resources/properties/claims/items/x-kubernetes-map-type
  value: atomic

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/targets/items/properties/volumes/items/properties/ephemeral/properties/volumeClaimTemplate/properties/spec/properties/resources/properties/claims/items/x-kubernetes-map-type
  value: atomic

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/targets/items/properties/resources/properties/claims/items/x-kubernetes-map-type
  value: atomic


#spec.validation.openAPIV3Schema.properties[spec].properties[targets].items.properties[sidecars].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: \"null\": must be atomic as item of a list with x-kubernetes-list-type=set, 
#spec.validation.openAPIV3Schema.properties[spec].properties[targets].items.properties[resources].properties[claims].items
#spec.validation.openAPIV3Schema.properties[spec].properties[targets].items.properties[volumes].items.properties[ephemeral].properties[volumeClaimTemplate].properties[spec].properties[resources].properties[claims].items.x-kubernetes-map-type
#spec.validation.openAPIV3Schema.properties[spec].properties[targets].items.properties[resources].properties[claims].items