// Copyright © 2019 A Medium Corporation.
// Licensed under the Apache License, Version 2.0; see the LICENSE file.

// Code generated by client. DO NOT EDIT.

// This package contains the scheme of the automatically generated clientset.
package scheme
