// Copyright © 2019 A Medium Corporation.
// Licensed under the Apache License, Version 2.0; see the LICENSE file.

// Code generated by lister. DO NOT EDIT.

package v1alpha1

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterNamespaceListerExpansion allows custom methods to be added to
// ClusterNamespaceLister.
type ClusterNamespaceListerExpansion interface{}

// IncarnationListerExpansion allows custom methods to be added to
// IncarnationLister.
type IncarnationListerExpansion interface{}

// IncarnationNamespaceListerExpansion allows custom methods to be added to
// IncarnationNamespaceLister.
type IncarnationNamespaceListerExpansion interface{}

// RevisionListerExpansion allows custom methods to be added to
// RevisionLister.
type RevisionListerExpansion interface{}

// RevisionNamespaceListerExpansion allows custom methods to be added to
// RevisionNamespaceLister.
type RevisionNamespaceListerExpansion interface{}
