// Copyright © 2019 A Medium Corporation.
// Licensed under the Apache License, Version 2.0; see the NOTICE file.

// Code generated by client. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.medium.engineering/picchu/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMirrors implements MirrorInterface
type FakeMirrors struct {
	Fake *FakePicchuV1alpha1
	ns   string
}

var mirrorsResource = schema.GroupVersionResource{Group: "picchu.medium.engineering", Version: "v1alpha1", Resource: "mirrors"}

var mirrorsKind = schema.GroupVersionKind{Group: "picchu.medium.engineering", Version: "v1alpha1", Kind: "Mirror"}

// Get takes name of the mirror, and returns the corresponding mirror object, and an error if there is any.
func (c *FakeMirrors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Mirror, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mirrorsResource, c.ns, name), &v1alpha1.Mirror{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mirror), err
}

// List takes label and field selectors, and returns the list of Mirrors that match those selectors.
func (c *FakeMirrors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MirrorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mirrorsResource, mirrorsKind, c.ns, opts), &v1alpha1.MirrorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MirrorList{ListMeta: obj.(*v1alpha1.MirrorList).ListMeta}
	for _, item := range obj.(*v1alpha1.MirrorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mirrors.
func (c *FakeMirrors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mirrorsResource, c.ns, opts))

}

// Create takes the representation of a mirror and creates it.  Returns the server's representation of the mirror, and an error, if there is any.
func (c *FakeMirrors) Create(ctx context.Context, mirror *v1alpha1.Mirror, opts v1.CreateOptions) (result *v1alpha1.Mirror, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mirrorsResource, c.ns, mirror), &v1alpha1.Mirror{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mirror), err
}

// Update takes the representation of a mirror and updates it. Returns the server's representation of the mirror, and an error, if there is any.
func (c *FakeMirrors) Update(ctx context.Context, mirror *v1alpha1.Mirror, opts v1.UpdateOptions) (result *v1alpha1.Mirror, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mirrorsResource, c.ns, mirror), &v1alpha1.Mirror{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mirror), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMirrors) UpdateStatus(ctx context.Context, mirror *v1alpha1.Mirror, opts v1.UpdateOptions) (*v1alpha1.Mirror, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mirrorsResource, "status", c.ns, mirror), &v1alpha1.Mirror{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mirror), err
}

// Delete takes name of the mirror and deletes it. Returns an error if one occurs.
func (c *FakeMirrors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mirrorsResource, c.ns, name), &v1alpha1.Mirror{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMirrors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mirrorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MirrorList{})
	return err
}

// Patch applies the patch and returns the patched mirror.
func (c *FakeMirrors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Mirror, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mirrorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Mirror{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mirror), err
}
